repos:
-   repo: https://github.com/python-poetry/poetry
    rev: 1.6.0
    hooks:
    -   id: poetry-check

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.3
  hooks:
    - id: ruff
      args: [--fix, --exit-non-zero-on-fix]
    - id: ruff-format  

- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.9.0
  hooks:
  - id: mypy
    additional_dependencies: [types-click, types-pytz]
    args: ["--install-types", "--non-interactive", "--ignore-missing-imports"]
    exclude: |
      (?x)^(
          scripts/.*|
          docs/.*|
          tests/.*|
          test\.py
      )$
